# Generated by Django 5.1.7 on 2025-05-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
