# Generated by Django 5.0.7 on 2025-05-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_nguoidung_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='confirmed_by',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
