# Generated by Django 5.0.7 on 2025-03-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_volunteer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='contact',
            new_name='contactt',
        ),
    ]
