# Generated by Django 5.0.7 on 2025-03-16 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_contact_donor_contactt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='contactt',
            new_name='contact',
        ),
    ]
