# Generated by Django 5.0.7 on 2025-03-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_contactt_donor_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='address',
        ),
    ]
