# Generated by Django 5.0.7 on 2025-03-16 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_donor_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='aboutme',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='adminremark',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='idpic',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='updationdate',
        ),
    ]
