# Generated by Django 5.1.7 on 2025-03-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_beneficiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='userpic',
            field=models.ImageField(blank=True, null=True, upload_to='beneficiary'),
        ),
    ]
